/*
	Generated by DFL Designer 0.3
	DFL Designer written by Christopher E. Miller
	www.dprogramming.com

	This source code is public domain.
*/

// To compile:
// 	dfl combo -gui

private import os.win.gui.all;


class ComboForm: Form
{
	ComboBox cbox;
	Button okBtn;
	
	this()
	{
		initializeComboForm();
		
		with(cbox = new ComboBox)
		{
			font = new Font("Tahoma", 9);
			text = "Выберите Месяц";
			width = 120;
			items.add("Январь");
			items.add("Февраль");
			items.add("Март");
			items.add("Апрель");
			items.add("Май");
			items.add("Июнь");
			items.add("Июль");
			items.add("Август");
			items.add("Сентябрь");
			items.add("Октябрь");
			items.add("Ноябрь");
			items.add("Декабрь");
			
			parent = this;
		}
		
		with(okBtn = new Button)
		{
			text = "OK";
			left = cbox.right + 4;
			
			parent = this;
			
			click ~= &onOkClick;
		}
		
		acceptButton = okBtn;
	}
	
	
	private void onOkClick(Object sender, EventArgs ea)
	{
		Object selItem;
		selItem = cbox.selectedItem;
		
		if(selItem)
		{
			msgBox(selItem.toString(), "Месяц",
				MsgBoxButtons.OK, MsgBoxIcon.INFORMATION);
		}
		else
		{
			msgBox("Вначале выберите месяц, пжалста.", "Ой!",
				MsgBoxButtons.OK, MsgBoxIcon.INFORMATION);
		}
	}
	
	
	private void initializeComboForm()
	{
		// Do not manually edit this block of code.
		//~DFL Designer 0.3 code begins here.
		
		//~DFL MainForm
		startPosition = FormStartPosition.CENTER_SCREEN;
		text = "Пример с Комбо-Боксом (выпадающим списком)";
		clientSize = os.win.gui.drawing.Size(292, 273);
		location = os.win.gui.drawing.Point(0, 0);
		
		//~DFL Designer 0.3 code ends here.
	}
}


int main()
{
	int result = 0;
	
	try
	{
		// Application initialization code here.
		
		Application.enableVisualStyles();
		Application.run(new ComboForm);
	}
	catch(Object o)
	{
		msgBox(o.toString(), "Fatal Error", MsgBoxButtons.OK, MsgBoxIcon.ERROR);
		
		result = 1;
	}
	
	return result;
}

