/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dwt.all;
import dwt.widgets.Display, dwt.widgets.Shell;
import dwt.graphics.Color, dwt.graphics.Rectangle;
import dwt.widgets.MessageBox;


class MyShell
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dwt.widgets.Shell.Shell shell;
	dwt.widgets.Label.Label label1;
	dwt.widgets.Button.Button button1;
	//~Entice Designer variables end here.
	
	
	this(dwt.widgets.Display.Display display)
	{
		initializeMyShell(display);
		
		//@  Other MyShell initialization code here.
		
	}
	
	
	private void initializeMyShell(dwt.widgets.Display.Display display)
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DWT Shell
		shell = new dwt.widgets.Shell.Shell(display,DWT.CLOSE|DWT.TITLE|DWT.MIN|DWT.MAX|DWT.RESIZE);
		shell.setBounds(0, 0, 300, 184);
		//~DWT dwt.widgets.Label.Label=label1
		label1 = new dwt.widgets.Label.Label(shell,DWT.LEFT);
		label1.setText("Salut!");
		label1.setBounds(64, 32, 60, 15);
		//~DWT dwt.widgets.Button.Button=button1 check
		button1 = new dwt.widgets.Button.Button(shell,DWT.CHECK);
		button1.setText("Check Out");
		button1.setBounds(88, 80, 75, 23);
		//~Entice Designer 0.8.5.02 code ends here.
	}
}


int main()
{
	int result = 0;
	
	try
	{
		dwt.widgets.Display.Display display = new dwt.widgets.Display.Display();
		
		//@  Other application initialization code here.
		
		MyShell eshell = new MyShell(display);
		eshell.shell.open();
		while(!eshell.shell.isDisposed())
		{
			if(!display.readAndDispatch())
				display.sleep();
		}
		display.dispose();
	}
	catch(Object o)
	{
		dwt.widgets.MessageBox.MessageBox.showError(o.toString(), "Fatal Error");
		
		result = 1;
	}
	
	return result;
}

